name: 002_xrestormer_denoise
model_type: XRestormerModel
scale: 1
num_gpu: 8
manual_seed: 123
padding_size: 64

# dataset and data loader settings
datasets:
  test_1:
    name: test
    type: SingleImageDataset
    dataroot_lq: ~
    sigma_test: 50
    in_ch: 3  ## RGB image
    io_backend:
      type: disk

# network structures
network_g:
  type: XRestormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [2,4,4,4]
  num_refinement_blocks: 4
  channel_heads: [1,2,4,8]
  spatial_heads: [1,2,4,8]
  overlap_ratio: [0.5,0.5,0.5,0.5]
  window_size: 8
  spatial_dim_head: 16
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False
  scale: 1

# path
path:
  pretrain_network_g: X-Restormer/experiments/pretrained/denoise_300k.pth
  strict_load_g: true
  resume_state: ~
  results: ~
# validation settings
val:
  save_img: true
  suffix: ~


# dist training settings
dist_params:
  backend: nccl
  port: 29500