GPT:
  API_KEY: "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"
  MODEL: "gpt-4-turbo"
  MAX_TOKENS: 3000
  TEMPERATURE: 0.0

LLAMA:
  API_KEY: "f2314811-1d95-4304-abc8-905c8b7c839d"
  MODEL: "llama3.1-405b"
  MAX_TOKENS: 3000
  TEMPERATURE: 0.0
